jobs:
  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    timeoutInMinutes: 360
    steps:
      - script: echo teste  # Template reference

  - job: macOS
    pool:
      vmImage: 'macOS-10.14'
    timeoutInMinutes: 360
    steps:
      - script: echo teste  # Template reference

  - job: Windows
    pool:
      vmImage: 'windows-latest'
    timeoutInMinutes: 360
    steps:
      - script: |
          git submodule update --init --recursive
        displayName: 'git submodule init'

      - task: jungeriusit.jungit-choco.jungit-chocoinstalled.ChocolateyInstaller@1
        displayName: 'Install/Upgrade Chocolatey'
        inputs:
          upgradeIfNeeded: true
        continueOnError: true
        timeoutInMinutes: 30

      - task: jungeriusit.jungit-choco.jungit-chocoinstaller.ChocoInstallPackage@1
        displayName: 'Install msys2'
        inputs:
          packageId: msys2
        continueOnError: true
        timeoutInMinutes: 30

      - script: 'C:\tools\msys64\usr\bin\sh.exe scripts\mingw-install-toolkit.sh'
        displayName: 'Install toolkit'

      - script: 'C:\tools\msys64\usr\bin\sh.exe scripts\mingw-build.sh'
        displayName: Build
